name: Transfer files & start docker compose

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Transfer files to remote
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.DO_HOST }}
          port: 22
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }} 
          local_path: './transfer/*'
          remote_path: '/root/'
      - name: Deploy Compose on DigitalOcean
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          user: ${{ secrets.DO_USERNAME }}
          pass: ${{ secrets.DO_PASSWORD }}
          command: |
            docker-compose down --remove-orphans
            docker-compose pull
            docker-compose -f docker-compose.yml up -d --build